codecov:
  notify:
    require_ci_to_pass: no

fixes:
  - "deps/nuraft_mesg/::"

ignore:
  - "deps/sisl/**"
  - "**/*_test.c*"
  - "**/*_test.h*"
  - "**/*_generated.h"
  - "**/*.pb.cc"
  - "**/*.pb.h"
  - "**/tests/*"
  - "**/jungle_logstore/*"
  - "**/flatb/*"
