name: NuraftMesg Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev/v5*
  pull_request:
    branches:
      - dev/v5.x
jobs:
  GccAddressSanitize:
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: "ubuntu-24.04"
      build-type: "Debug"
      malloc-impl: "libc"
      compiler: "gcc"
      conan-channel: "dev"
      tooling: "AddressSanitize"

  GccThreadSanitize:
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: "ubuntu-24.04"
      build-type: "Debug"
      malloc-impl: "libc"
      compiler: "gcc"
      conan-channel: "dev"
      tooling: "ThreadSanitize"

  GccCoverage:
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: "ubuntu-24.04"
      build-type: "Debug"
      malloc-impl: "libc"
      compiler: "gcc"
      conan-channel: "dev"
      tooling: "Coverage"

  GccRelease:
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: "ubuntu-24.04"
      build-type: "Release"
      malloc-impl: "tcmalloc"
      compiler: "gcc"
      conan-channel: "dev"
      tooling: "None"

  ChainBuild:
    runs-on: "ubuntu-24.04"
    steps:
    - name: Start HomeStore Build
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHAIN_BUILD_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/eBay/homestore/actions/workflows/merge_build.yml/dispatches \
          -d '{"ref":"dev/v8.x","inputs":{}}'
      if: ${{ github.ref == 'refs/heads/dev/v8.x' }}
